# Linear SVM

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import datasets

iris = datasets.load_iris(as_frame = True)
X = iris.data[["petal length (cm)", "petal width (cm)"]].values
y = iris.target

setosa_or_versicolor = (y == 0) | (y == 1)

X = X[setosa_or_versicolor]
y = y[setosa_or_versicolor]

svm_clf = SVC(kernel = 'linear', C = 1e100)
svm_clf.fit(X,y)

SVC(C=1e+100, kernel='linear')

In [4]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

X = iris.data[["petal length (cm)", "petal width (cm)"]].values
y = (iris.target ==2)

svm_clf = make_pipeline(StandardScaler(),LinearSVC(C = 1, random_state=42))
svm_clf.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(C=1, random_state=42))])

In [5]:
X_new = [[5.5,1.7],[5,1.5]]
svm_clf.predict(X_new)

array([ True, False])

In [6]:
svm_clf.decision_function(X_new)

array([ 0.66163411, -0.22036063])

In [7]:
from sklearn.datasets import make_moons
from sklearn.preprocessing import PolynomialFeatures

X,y = make_moons(n_samples = 100,noise = 0.15,random_state = 42)
polynomial_svm = make_pipeline(
    PolynomialFeatures(degree = 2),
    StandardScaler(),
    LinearSVC(C = 10,max_iter=10_00,dual=True,random_state=42)
)
polynomial_svm.fit(X,y)

C:\Users\aqili\AppData\Local\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(C=10, random_state=42))])

# Poly Kernel

In [10]:
from sklearn.svm import SVC

poly_kernel_svm_clf = make_pipeline(
    StandardScaler(),
    SVC(kernel = 'poly',degree = 3,C = 5,coef0 = 1)
)
poly_kernel_svm_clf.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(C=5, coef0=1, kernel='poly'))])

In [19]:
poly_kernel_svm_clf.score(X,y)

0.98

# SVM Regression

In [26]:
from sklearn.svm import LinearSVR

np.random.seed(42)
X = 2* np.random.rand(50,1)
y = 4+3*X[:,0]+np.random.randn(50)

svm_reg = make_pipeline(
    StandardScaler(),LinearSVR(epsilon = 0.5)
)
svm_reg.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvr', LinearSVR(epsilon=0.5))])

In [32]:
svm_reg.predict([[4]])

array([15.69997619])

In [40]:
from sklearn.svm import SVR

X = 2*np.random.rand(50,1)-1
y = 0.2+0.1*X[:,0] +X[:,0]**2 +np.random.randn(50)/10

svm_poly_reg = make_pipeline(
    StandardScaler(),
    SVR(kernel = 'poly',degree = 2,C = 5,coef0 = 1)
)
svm_poly_reg.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(C=5, coef0=1, degree=2, kernel='poly'))])

In [42]:
svm_poly_reg.score(X,y)

0.9103974005600055